server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  thymeleaf:
    prefix: /WEB-INF/pages/
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    suffix: .html
  datasource:
    url: jdbc:mysql://120.25.58.129:3306/tongyeyun?useUnicode=true&characterEncoding=UTF-8&zerodatetimebehavior=converttonull&allowMultiQueries=true
    username: ymdu
    password: e589C@q#E@l6J@Qb
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.showSqlMillis=5000
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: 120.25.58.129
    password: Yieldmore2014
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1